//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internal_System.MarketDataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponsePM", Namespace="http://schemas.datacontract.org/2004/07/ExchangeSystem")]
    [System.SerializableAttribute()]
    public partial class ResponsePM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymbolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MarketDataService.IMarketDataService")]
    public interface IMarketDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketDataService/GetWholeData", ReplyAction="http://tempuri.org/IMarketDataService/GetWholeDataResponse")]
        Internal_System.MarketDataService.ResponsePM[] GetWholeData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketDataService/GetWholeData", ReplyAction="http://tempuri.org/IMarketDataService/GetWholeDataResponse")]
        System.Threading.Tasks.Task<Internal_System.MarketDataService.ResponsePM[]> GetWholeDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketDataService/GetSymbolData", ReplyAction="http://tempuri.org/IMarketDataService/GetSymbolDataResponse")]
        Internal_System.MarketDataService.ResponsePM GetSymbolData(string symbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketDataService/GetSymbolData", ReplyAction="http://tempuri.org/IMarketDataService/GetSymbolDataResponse")]
        System.Threading.Tasks.Task<Internal_System.MarketDataService.ResponsePM> GetSymbolDataAsync(string symbol);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMarketDataServiceChannel : Internal_System.MarketDataService.IMarketDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MarketDataServiceClient : System.ServiceModel.ClientBase<Internal_System.MarketDataService.IMarketDataService>, Internal_System.MarketDataService.IMarketDataService {
        
        public MarketDataServiceClient() {
        }
        
        public MarketDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MarketDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarketDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarketDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Internal_System.MarketDataService.ResponsePM[] GetWholeData() {
            return base.Channel.GetWholeData();
        }
        
        public System.Threading.Tasks.Task<Internal_System.MarketDataService.ResponsePM[]> GetWholeDataAsync() {
            return base.Channel.GetWholeDataAsync();
        }
        
        public Internal_System.MarketDataService.ResponsePM GetSymbolData(string symbol) {
            return base.Channel.GetSymbolData(symbol);
        }
        
        public System.Threading.Tasks.Task<Internal_System.MarketDataService.ResponsePM> GetSymbolDataAsync(string symbol) {
            return base.Channel.GetSymbolDataAsync(symbol);
        }
    }
}
