//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internal_System.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/ExchangeSystem")]
    [System.SerializableAttribute()]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BlockIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long QtyAllocatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long QtyRequestedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequestIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SideField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Internal_System.ServiceReference1.Status StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short StatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Internal_System.ServiceReference1.StockData StockDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TraderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BlockID {
            get {
                return this.BlockIDField;
            }
            set {
                if ((this.BlockIDField.Equals(value) != true)) {
                    this.BlockIDField = value;
                    this.RaisePropertyChanged("BlockID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long QtyAllocated {
            get {
                return this.QtyAllocatedField;
            }
            set {
                if ((this.QtyAllocatedField.Equals(value) != true)) {
                    this.QtyAllocatedField = value;
                    this.RaisePropertyChanged("QtyAllocated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long QtyRequested {
            get {
                return this.QtyRequestedField;
            }
            set {
                if ((this.QtyRequestedField.Equals(value) != true)) {
                    this.QtyRequestedField = value;
                    this.RaisePropertyChanged("QtyRequested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequestID {
            get {
                return this.RequestIDField;
            }
            set {
                if ((this.RequestIDField.Equals(value) != true)) {
                    this.RequestIDField = value;
                    this.RaisePropertyChanged("RequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Side {
            get {
                return this.SideField;
            }
            set {
                if ((object.ReferenceEquals(this.SideField, value) != true)) {
                    this.SideField = value;
                    this.RaisePropertyChanged("Side");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Internal_System.ServiceReference1.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Internal_System.ServiceReference1.StockData StockData {
            get {
                return this.StockDataField;
            }
            set {
                if ((object.ReferenceEquals(this.StockDataField, value) != true)) {
                    this.StockDataField = value;
                    this.RaisePropertyChanged("StockData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TraderID {
            get {
                return this.TraderIDField;
            }
            set {
                if ((this.TraderIDField.Equals(value) != true)) {
                    this.TraderIDField = value;
                    this.RaisePropertyChanged("TraderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/ExchangeSystem")]
    [System.SerializableAttribute()]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Internal_System.ServiceReference1.ServiceRequest[] ServiceRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short StatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Internal_System.ServiceReference1.Transaction[] TransactionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Internal_System.ServiceReference1.ServiceRequest[] ServiceRequests {
            get {
                return this.ServiceRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceRequestsField, value) != true)) {
                    this.ServiceRequestsField = value;
                    this.RaisePropertyChanged("ServiceRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusName {
            get {
                return this.StatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusNameField, value) != true)) {
                    this.StatusNameField = value;
                    this.RaisePropertyChanged("StatusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Internal_System.ServiceReference1.Transaction[] Transactions {
            get {
                return this.TransactionsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionsField, value) != true)) {
                    this.TransactionsField = value;
                    this.RaisePropertyChanged("Transactions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockData", Namespace="http://schemas.datacontract.org/2004/07/ExchangeSystem")]
    [System.SerializableAttribute()]
    public partial class StockData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MarketPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long QuantityAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Internal_System.ServiceReference1.ServiceRequest[] ServiceRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Internal_System.ServiceReference1.Transaction[] TransactionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarketPrice {
            get {
                return this.MarketPriceField;
            }
            set {
                if ((this.MarketPriceField.Equals(value) != true)) {
                    this.MarketPriceField = value;
                    this.RaisePropertyChanged("MarketPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long QuantityAvailable {
            get {
                return this.QuantityAvailableField;
            }
            set {
                if ((this.QuantityAvailableField.Equals(value) != true)) {
                    this.QuantityAvailableField = value;
                    this.RaisePropertyChanged("QuantityAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Internal_System.ServiceReference1.ServiceRequest[] ServiceRequests {
            get {
                return this.ServiceRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceRequestsField, value) != true)) {
                    this.ServiceRequestsField = value;
                    this.RaisePropertyChanged("ServiceRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Internal_System.ServiceReference1.Transaction[] Transactions {
            get {
                return this.TransactionsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionsField, value) != true)) {
                    this.TransactionsField = value;
                    this.RaisePropertyChanged("Transactions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceRequest", Namespace="http://schemas.datacontract.org/2004/07/ExchangeSystem")]
    [System.SerializableAttribute()]
    public partial class ServiceRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://schemas.datacontract.org/2004/07/ExchangeSystem")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BlockIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long QtyAllocatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long QtyRequestedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SideField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Internal_System.ServiceReference1.Status StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short StatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Internal_System.ServiceReference1.StockData StockDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TraderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TransactionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BlockID {
            get {
                return this.BlockIDField;
            }
            set {
                if ((this.BlockIDField.Equals(value) != true)) {
                    this.BlockIDField = value;
                    this.RaisePropertyChanged("BlockID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long QtyAllocated {
            get {
                return this.QtyAllocatedField;
            }
            set {
                if ((this.QtyAllocatedField.Equals(value) != true)) {
                    this.QtyAllocatedField = value;
                    this.RaisePropertyChanged("QtyAllocated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long QtyRequested {
            get {
                return this.QtyRequestedField;
            }
            set {
                if ((this.QtyRequestedField.Equals(value) != true)) {
                    this.QtyRequestedField = value;
                    this.RaisePropertyChanged("QtyRequested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Side {
            get {
                return this.SideField;
            }
            set {
                if ((object.ReferenceEquals(this.SideField, value) != true)) {
                    this.SideField = value;
                    this.RaisePropertyChanged("Side");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Internal_System.ServiceReference1.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Internal_System.ServiceReference1.StockData StockData {
            get {
                return this.StockDataField;
            }
            set {
                if ((object.ReferenceEquals(this.StockDataField, value) != true)) {
                    this.StockDataField = value;
                    this.RaisePropertyChanged("StockData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TraderID {
            get {
                return this.TraderIDField;
            }
            set {
                if ((this.TraderIDField.Equals(value) != true)) {
                    this.TraderIDField = value;
                    this.RaisePropertyChanged("TraderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransactionID {
            get {
                return this.TransactionIDField;
            }
            set {
                if ((this.TransactionIDField.Equals(value) != true)) {
                    this.TransactionIDField = value;
                    this.RaisePropertyChanged("TransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/ExchangeSystem")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BlockIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long QtyAllocatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long QtyRequestedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequestIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SideField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Internal_System.ServiceReference1.Status StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short StatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Internal_System.ServiceReference1.StockData StockDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TraderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BlockID {
            get {
                return this.BlockIDField;
            }
            set {
                if ((this.BlockIDField.Equals(value) != true)) {
                    this.BlockIDField = value;
                    this.RaisePropertyChanged("BlockID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long QtyAllocated {
            get {
                return this.QtyAllocatedField;
            }
            set {
                if ((this.QtyAllocatedField.Equals(value) != true)) {
                    this.QtyAllocatedField = value;
                    this.RaisePropertyChanged("QtyAllocated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long QtyRequested {
            get {
                return this.QtyRequestedField;
            }
            set {
                if ((this.QtyRequestedField.Equals(value) != true)) {
                    this.QtyRequestedField = value;
                    this.RaisePropertyChanged("QtyRequested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequestID {
            get {
                return this.RequestIDField;
            }
            set {
                if ((this.RequestIDField.Equals(value) != true)) {
                    this.RequestIDField = value;
                    this.RaisePropertyChanged("RequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Side {
            get {
                return this.SideField;
            }
            set {
                if ((object.ReferenceEquals(this.SideField, value) != true)) {
                    this.SideField = value;
                    this.RaisePropertyChanged("Side");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Internal_System.ServiceReference1.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Internal_System.ServiceReference1.StockData StockData {
            get {
                return this.StockDataField;
            }
            set {
                if ((object.ReferenceEquals(this.StockDataField, value) != true)) {
                    this.StockDataField = value;
                    this.RaisePropertyChanged("StockData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TraderID {
            get {
                return this.TraderIDField;
            }
            set {
                if ((this.TraderIDField.Equals(value) != true)) {
                    this.TraderIDField = value;
                    this.RaisePropertyChanged("TraderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITraderFillService")]
    public interface ITraderFillService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraderFillService/GetData", ReplyAction="http://tempuri.org/ITraderFillService/GetDataResponse")]
        Internal_System.ServiceReference1.Response GetData(Internal_System.ServiceReference1.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraderFillService/GetData", ReplyAction="http://tempuri.org/ITraderFillService/GetDataResponse")]
        System.Threading.Tasks.Task<Internal_System.ServiceReference1.Response> GetDataAsync(Internal_System.ServiceReference1.Request request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITraderFillServiceChannel : Internal_System.ServiceReference1.ITraderFillService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TraderFillServiceClient : System.ServiceModel.ClientBase<Internal_System.ServiceReference1.ITraderFillService>, Internal_System.ServiceReference1.ITraderFillService {
        
        public TraderFillServiceClient() {
        }
        
        public TraderFillServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TraderFillServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TraderFillServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TraderFillServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Internal_System.ServiceReference1.Response GetData(Internal_System.ServiceReference1.Request request) {
            return base.Channel.GetData(request);
        }
        
        public System.Threading.Tasks.Task<Internal_System.ServiceReference1.Response> GetDataAsync(Internal_System.ServiceReference1.Request request) {
            return base.Channel.GetDataAsync(request);
        }
    }
}
