//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internal_System.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block_status
    {
        public Block_status()
        {
            this.Blocks = new HashSet<Block>();
        }
    
        public long BlockStatusId { get; set; }
        public string StatusName { get; set; }
        public bool ISActive { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime UpdationDate { get; set; }
    
        public virtual ICollection<Block> Blocks { get; set; }
    }
}
