//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internal_System.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symbol_Properties
    {
        public Symbol_Properties()
        {
            this.Blocks = new HashSet<Block>();
            this.Orders = new HashSet<Order>();
        }
    
        public long SymbolID { get; set; }
        public string Symbol { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ICollection<Block> Blocks { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
