//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.ServiceRequests = new HashSet<ServiceRequest>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public short StatusID { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
